export const EventType = {
    USER_JOIN: "USER_JOIN",
    USER_LEAVE: "USER_LEAVE",
    USER_KICK: "USER_KICK",
    USER_BAN: "USER_BAN",
    USER_MUTE: "USER_MUTE",
    MESSAGE_STARTED: "MESSAGE_STARTED",
    MESSAGE_ENDED: "MESSAGE_ENDED",
    ROOM_CREATE: "ROOM_CREATE",
    ROOM_EXPIRED: "ROOM_EXPIRED",
    ROOM_SETTINGS_CHANGE: "ROOM_SETTINGS_CHANGE",
    SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT"
} as const;
export type EventType = (typeof EventType)[keyof typeof EventType];
